import { RequiredDataFromCollectionSlug } from 'payload';

import type { ProductArgs } from './product-1';

export const product2: (args: ProductArgs) => RequiredDataFromCollectionSlug<'products'> = ({
  heroImage1,
  heroImage2,
  heroImage3,
  heroImage4,
  heroImage5,
  blockImage,
  pdfDoc,
  author,
}) => {
  return {
    slug: 'high-energy-feed-corn',
    _status: 'published',
    slugLock: false,
    authors: [author],

    shortDescription:
      'Кукурудза фуражна з високим енергетичним потенціалом та збалансованим складом поживних речовин для тваринництва.',
    itemCode: 'CORN-FEED-002',
    price: '220-240 USD/т FOB порт',
    availability: 'in_stock' as const,
    ratingEnabled: true,
    rating: 5,
    reviewsCount: 32,
    features: [
      { feature: 'Обмінна енергія 13.2 МДж/кг' },
      { feature: 'Сирий протеїн 9.5%' },
      { feature: 'Вологість не більше 15%' },
      { feature: 'Афлатоксин В1 < 5 мкг/кг' },
      { feature: 'Без ГМО' },
      { feature: 'Підвищена засвоюваність' },
    ],
    images: [
      { image: heroImage1.id },
      { image: heroImage2.id },
      { image: heroImage3.id },
      { image: heroImage4.id },
      { image: heroImage5.id },
    ],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Кукурудза кормова з підвищеною енергетичною цінністю для тваринництва та птахівництва.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Поживна цінність',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 1,
                          mode: 'normal',
                          style: '',
                          text: 'Енергетичні показники:',
                          version: 1,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' Обмінна енергія 13.2 МДж/кг, сирий протеїн 9.5%, жир 4.2%. Ідеально підходить для годівлі великої рогатої худоби та свиней.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'warning',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Спеціалізована кормова кукурудза',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Наша кормова кукурудза вирощується спеціально для тваринництва з використанням гібридів з підвищеним вмістом енергії та поживних речовин. Ретельно контрольована технологія вирощування забезпечує оптимальний баланс поживних елементів для максимальної засвоюваності тваринами.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Особлива увага приділяється мінімізації мікотоксинів та забруднювачів, які можуть негативно вплинути на здоров'я тварин. Кожна партія проходить ретельний аналіз на вміст афлатоксинів, зеараленону та інших шкідливих речовин.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Переваги для різних видів тварин',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h3',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Для великої рогатої худоби наша кукурудза забезпечує високий рівень енергії, необхідний для підтримання молочної продуктивності та набору ваги. Для свиней - оптимальний баланс енергії та протеїну сприяє ефективному росту. У птахівництві кукурудза використовується як основна енергетична складова раціону.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Наші фахівці з годівлі тварин надають безкоштовні консультації щодо оптимального використання кукурудзи в раціонах для різних видів тварин та птиці.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Безпека та якість',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: "Вся наша кормова кукурудза проходить обов'язкове тестування на вміст мікотоксинів, важких металів та пестицидів. Ми гарантуємо повну безпеку продукції для здоров'я тварин та якість кінцевої продукції тваринництва.",
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'success',
            },
            format: '',
            version: 2,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage1.id,
    meta: {
      description:
        'Кормова кукурудза з підвищеною енергетичною цінністю для тваринництва. Обмінна енергія 13.2 МДж/кг, безпечна для тварин, без мікотоксинів. Ідеально для ВРХ, свиней та птиці.',
      image: heroImage1.id,
      title: 'Кукурудза кормова високоенергетична',
    },
    relatedPosts: [],
    title: 'Кукурудза кормова високоенергетична',
    fullDescription: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                text: 'Спеціалізована кормова кукурудза для тваринництва',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Наша кормова кукурудза - це спеціально відібрані гібриди з підвищеним вмістом енергії та оптимальним поєднанням поживних речовин. Вирощена за унікальною технологією, що забезпечує максимальну засвоюваність тваринами.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: "Ідеально підходить для всіх видів сільськогосподарських тварин: ВРХ, свинарство, птахівництво. Забезпечує швидкий ріст, високу молочну продуктивність та якісне м'ясо.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    specifications: [
      { name: 'Обмінна енергія', value: '13.2 МДж/кг' },
      { name: 'Сирий протеїн', value: '9.5%' },
      { name: 'Сирий жир', value: '4.2%' },
      { name: 'Сира клітковина', value: '2.8%' },
      { name: 'Сира зола', value: '1.4%' },
      { name: 'Вологість', value: 'не більше 15%' },
      { name: 'Кальцій', value: '0.05%' },
      { name: 'Фосфор', value: '0.25%' },
      { name: 'Лізин', value: '0.28%' },
      { name: 'Метіонін', value: '0.16%' },
      { name: 'Афлатоксин B1', value: 'менше 5 мкг/кг' },
      { name: 'Зеараленон', value: 'менше 100 мкг/кг' },
    ],
    additionalSpecifications: [
      {
        icon: 'LuActivity',
        name: 'Енергетична цінність',
        description: 'Висока обмінна енергія забезпечує максимальну продуктивність тварин',
      },
      {
        icon: 'LuShield',
        name: 'Мікробіологічна безпека',
        description: 'Контроль на сальмонелу, E.coli та інші патогенні мікроорганізми',
      },
      {
        icon: 'LuLeaf',
        name: 'Природний склад',
        description: 'Без штучних добавок, консервантів та стимуляторів росту',
      },
      {
        icon: 'LuPackage',
        name: 'Фасування та зберігання',
        description: 'Доступно насипом, в big-bag або мішках по 25/50 кг',
      },
    ],
    documents: [
      {
        name: 'Сертифікат на кормові добавки',
        file: pdfDoc.id,
        type: 'PDF' as const,
      },
      {
        name: 'Протокол аналізу поживності',
        file: pdfDoc.id,
        type: 'PDF' as const,
      },
      {
        name: 'Рекомендації по годівлі',
        file: pdfDoc.id,
        type: 'PDF' as const,
      },
      {
        name: 'Ветеринарний сертифікат',
        file: pdfDoc.id,
        type: 'PDF' as const,
      },
    ],
    benefits: [
      {
        icon: 'LuZap',
        title: 'Висока енергетичність',
        description: 'Максимальна обмінна енергія 13.2 МДж/кг для ефективного росту тварин',
      },
      {
        icon: 'LuShieldCheck',
        title: 'Безпека продукції',
        description: 'Ретельний контроль мікотоксинів та патогенних мікроорганізмів',
      },
      {
        icon: 'LuTarget',
        title: 'Збалансованість',
        description: 'Оптимальне співвідношення енергії та поживних речовин',
      },
    ],
  };
};

export const product2_en: (args: ProductArgs) => RequiredDataFromCollectionSlug<'products'> = ({
  heroImage1,
  heroImage2,
  heroImage3,
  heroImage4,
  heroImage5,
  blockImage,
  pdfDoc,
  author,
}) => {
  return {
    slug: 'high-energy-feed-corn',
    _status: 'published',
    slugLock: false,
    authors: [author],
    shortDescription:
      'Fodder corn with high energy potential and a balanced nutrient composition for livestock.',
    itemCode: 'CORN-FEED-002',
    price: '$220-240 USD/t FOB port',
    availability: 'in_stock' as const,
    ratingEnabled: true,
    rating: 5,
    reviewsCount: 32,
    features: [
      { feature: 'Metabolizable energy 13.2 MJ/kg' },
      { feature: 'Crude protein 9.5%' },
      { feature: 'Moisture no more than 15%' },
      { feature: 'Aflatoxin B1 < 5 μg/kg' },
      { feature: 'GMO-free' },
      { feature: 'Increased digestibility' },
    ],
    images: [
      { image: heroImage1.id },
      { image: heroImage2.id },
      { image: heroImage3.id },
      { image: heroImage4.id },
      { image: heroImage5.id },
    ],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Feed corn with increased energy value for livestock and poultry.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Nutritional Value',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 1,
                          mode: 'normal',
                          style: '',
                          text: 'Energy indicators:',
                          version: 1,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' Metabolizable energy 13.2 MJ/kg, crude protein 9.5%, fat 4.2%. Ideal for feeding cattle and pigs.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'warning',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Specialized Feed Corn',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our feed corn is grown specifically for livestock using hybrids with increased energy and nutrient content. A carefully controlled cultivation technology ensures an optimal balance of nutrients for maximum digestibility by animals.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Special attention is paid to minimizing mycotoxins and contaminants that can negatively affect animal health. Each batch undergoes a thorough analysis for aflatoxins, zearalenone, and other harmful substances.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Benefits for Different Animal Species',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h3',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'For cattle, our corn provides the high energy level necessary to maintain milk production and weight gain. For pigs, the optimal balance of energy and protein promotes efficient growth. In poultry farming, corn is used as the main energy component of the diet.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our animal nutrition specialists provide free consultations on the optimal use of corn in the diets for various types of animals and poultry.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Safety and Quality',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: 'All our feed corn undergoes mandatory testing for mycotoxins, heavy metals, and pesticides. We guarantee the complete safety of the product for animal health and the quality of the final livestock products.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'success',
            },
            format: '',
            version: 2,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage1.id,
    meta: {
      description:
        'Feed corn with increased energy value for livestock. Metabolizable energy 13.2 MJ/kg, safe for animals, free of mycotoxins. Ideal for cattle, pigs, and poultry.',
      image: heroImage1.id,
      title: 'High-Energy Feed Corn',
    },
    relatedPosts: [],
    title: 'High-Energy Feed Corn',
    fullDescription: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                text: 'Specialized Feed Corn for Livestock',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Our feed corn consists of specially selected hybrids with increased energy content and an optimal combination of nutrients. It is grown using a unique technology that ensures maximum digestibility by animals.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Ideal for all types of farm animals: cattle, pigs, poultry. It ensures rapid growth, high milk productivity, and quality meat.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    specifications: [
      { name: 'Metabolizable Energy', value: '13.2 MJ/kg' },
      { name: 'Crude Protein', value: '9.5%' },
      { name: 'Crude Fat', value: '4.2%' },
      { name: 'Crude Fiber', value: '2.8%' },
      { name: 'Crude Ash', value: '1.4%' },
      { name: 'Moisture', value: 'no more than 15%' },
      { name: 'Calcium', value: '0.05%' },
      { name: 'Phosphorus', value: '0.25%' },
      { name: 'Lysine', value: '0.28%' },
      { name: 'Methionine', value: '0.16%' },
      { name: 'Aflatoxin B1', value: 'less than 5 μg/kg' },
      { name: 'Zearalenone', value: 'less than 100 μg/kg' },
    ],
    additionalSpecifications: [
      {
        icon: 'LuActivity',
        name: 'Energy Value',
        description: 'High metabolizable energy ensures maximum animal productivity',
      },
      {
        icon: 'LuShield',
        name: 'Microbiological Safety',
        description: 'Controlled for Salmonella, E.coli, and other pathogenic microorganisms',
      },
      {
        icon: 'LuLeaf',
        name: 'Natural Composition',
        description: 'No artificial additives, preservatives, or growth stimulants',
      },
      {
        icon: 'LuPackage',
        name: 'Packaging and Storage',
        description: 'Available in bulk, in big-bags, or in 25/50 kg bags',
      },
    ],
    documents: [
      {
        name: 'Feed Additive Certificate',
        file: pdfDoc.id,
        type: 'PDF' as const,
      },
      {
        name: 'Nutrient Analysis Protocol',
        file: pdfDoc.id,
        type: 'PDF' as const,
      },
      {
        name: 'Feeding Recommendations',
        file: pdfDoc.id,
        type: 'PDF' as const,
      },
      {
        name: 'Veterinary Certificate',
        file: pdfDoc.id,
        type: 'PDF' as const,
      },
    ],
    benefits: [
      {
        icon: 'LuZap',
        title: 'High Energy',
        description: 'Maximum metabolizable energy of 13.2 MJ/kg for efficient animal growth',
      },
      {
        icon: 'LuShieldCheck',
        title: 'Product Safety',
        description: 'Thorough control of mycotoxins and pathogenic microorganisms',
      },
      {
        icon: 'LuTarget',
        title: 'Balanced',
        description: 'Optimal ratio of energy and nutrients',
      },
    ],
  };
};
